package taller;

import javax.swing.JOptionPane;

/**
 *
 * @author: JUAN RODRIGO
 */
public class Orden_Servicio extends javax.swing.JFrame {
    Marca mar = new Marca();
    Color col = new Color();
    Servicio_Ent serv = new Servicio_Ent();
  
    /**
     * Creates new form Orden_Servicio
     */
    public Orden_Servicio() {
        initComponents();
        
        setTitle("ORDEN DE SERVICIO");
        
        mar.Cargar_Marca();
        col.Cargar_Color();
        serv.hora_entrada();
        
        ob_marca.setEnabled(false);
        ob_color.setEnabled(false);
        btn_buscar_cliente.setEnabled(false);
        btn_cliente_nuevo.setEnabled(false);
        btn_tom_foto.setEnabled(false);
        btn_registrar.setEnabled(false);
        txt_marca.setVisible(false);
        txt_color.setVisible(false);
        txt_cliente.setEditable(false);
    }// Orden_Servicio
    
    public void limpiar(){
        txt_placa.setText("");
        txt_modelo.setText("");
        txt_color.setText("");
        txt_cliente.setText("");
        txt_nombre.setText("");
        txt_apellido.setText("");
        txt_email.setText("");
        txt_telefono.setText("");
        txt_domicilio.setText("");
        txt_diagnostico.setText("");
    }//limpiar
    
    public void restaurar(){
        ob_marca.setEnabled(true);
        ob_color.setEnabled(true);
        ob_marca.setVisible(true);
        ob_color.setVisible(true);
        txt_marca.setVisible(false);
        txt_color.setVisible(false);
        txt_marca.setEditable(true);
        txt_modelo.setEditable(true);
        txt_color.setEditable(true);
        txt_nombre.setEditable(true);
        txt_apellido.setEditable(true);
        txt_email.setEditable(false);
        txt_telefono.setEditable(false);
        txt_domicilio.setEditable(false);
    }// restaurar
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ob_marca = new javax.swing.JComboBox();
        txt_placa = new javax.swing.JTextField();
        btn_buscar_placa = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_modelo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ob_color = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_diagnostico = new javax.swing.JTextArea();
        txt_hora_ent = new javax.swing.JLabel();
        txt_marca = new javax.swing.JTextField();
        txt_color = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txt_cliente = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_apellido = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_telefono = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_domicilio = new javax.swing.JTextField();
        btn_buscar_cliente = new javax.swing.JButton();
        btn_cliente_nuevo = new javax.swing.JButton();
        btn_tom_foto = new javax.swing.JButton();
        btn_registrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("PLACA:");

        ob_marca.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ob_marca.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        txt_placa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_placa.setForeground(new java.awt.Color(0, 0, 255));
        txt_placa.setToolTipText("INGRESA PLACA");

        btn_buscar_placa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_buscar_placa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/page_find.png"))); // NOI18N
        btn_buscar_placa.setText("BUSCAR");
        btn_buscar_placa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_buscar_placa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscar_placaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("HORA ENTRADA:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("MARCA:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("MODELO: ");

        txt_modelo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_modelo.setForeground(new java.awt.Color(0, 0, 255));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("COLOR:");

        ob_color.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ob_color.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("DIAGNOSTICO:");

        txt_diagnostico.setColumns(20);
        txt_diagnostico.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        txt_diagnostico.setRows(5);
        jScrollPane1.setViewportView(txt_diagnostico);

        txt_hora_ent.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_hora_ent.setForeground(new java.awt.Color(0, 0, 204));
        txt_hora_ent.setText("--:--:--");

        txt_marca.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_marca.setForeground(new java.awt.Color(0, 0, 255));

        txt_color.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_color.setForeground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_placa, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ob_marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ob_color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_buscar_placa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_hora_ent))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1)))
                .addGap(46, 46, 46))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_placa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_buscar_placa)
                    .addComponent(jLabel2)
                    .addComponent(txt_hora_ent))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ob_marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txt_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(ob_color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel6))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(153, 255, 255));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("ID CLIENTE:");

        txt_cliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_cliente.setForeground(new java.awt.Color(0, 0, 255));
        txt_cliente.setToolTipText("INGRESA PLACA");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("NOMBRE:");

        txt_nombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_nombre.setForeground(new java.awt.Color(0, 0, 255));
        txt_nombre.setToolTipText("INGRESA PLACA");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("APELLIDOS:");

        txt_apellido.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_apellido.setForeground(new java.awt.Color(0, 0, 255));
        txt_apellido.setToolTipText("INGRESA PLACA");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("E-MAIL: ");

        txt_email.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_email.setForeground(new java.awt.Color(0, 0, 255));
        txt_email.setToolTipText("INGRESA PLACA");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("TELÉFONO:");

        txt_telefono.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_telefono.setForeground(new java.awt.Color(0, 0, 255));
        txt_telefono.setToolTipText("INGRESA PLACA");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("DOMICILIO:");

        txt_domicilio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_domicilio.setForeground(new java.awt.Color(0, 0, 255));
        txt_domicilio.setToolTipText("INGRESA PLACA");

        btn_buscar_cliente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_buscar_cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/report_magnify.png"))); // NOI18N
        btn_buscar_cliente.setText("BUSCAR");
        btn_buscar_cliente.setActionCommand("BUSCAR CLIENTE");
        btn_buscar_cliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_buscar_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscar_clienteActionPerformed(evt);
            }
        });

        btn_cliente_nuevo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_cliente_nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/group_add.png"))); // NOI18N
        btn_cliente_nuevo.setText("CLIENTE NUEVO");
        btn_cliente_nuevo.setActionCommand("BUSCAR CLIENTE");
        btn_cliente_nuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_cliente_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cliente_nuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_domicilio))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(11, 11, 11)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_email, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                                    .addComponent(txt_nombre))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 18, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(15, 15, 15))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_buscar_cliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_cliente_nuevo)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txt_telefono, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                                .addComponent(txt_apellido)))))
                .addGap(22, 22, 22))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_buscar_cliente)
                    .addComponent(btn_cliente_nuevo))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txt_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txt_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txt_domicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        btn_tom_foto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_tom_foto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/tomar_foto.png"))); // NOI18N
        btn_tom_foto.setText("TOMAR FOTO");
        btn_tom_foto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tom_fotoActionPerformed(evt);
            }
        });

        btn_registrar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_registrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/disk.png"))); // NOI18N
        btn_registrar.setText("REGISTRAR");
        btn_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_tom_foto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_registrar)
                        .addGap(22, 22, 22))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(138, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_tom_foto)
                    .addComponent(btn_registrar))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_tom_fotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tom_fotoActionPerformed
        new Camara().setVisible(true);
        btn_registrar.setEnabled(true); 
    }//GEN-LAST:event_btn_tom_fotoActionPerformed

    private void btn_buscar_placaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscar_placaActionPerformed
        if(txt_placa.getText().toUpperCase().trim().equals("")){
            JOptionPane.showMessageDialog(this, "CAMPO VACIO:  INGRESE UNA PLACA ", "BUSCANDO PLACA...", 0);
        } else {
            if(serv.buscar_placa(txt_placa.getText().toUpperCase().replace("'", "").replace(";", "").replace("=", "").trim()) == 1){
                JOptionPane.showMessageDialog(this, "PLACA ENCONTRADA");
                serv.valor1 = 1;
                ob_marca.setVisible(false);
                ob_color.setVisible(false);
                txt_marca.setVisible(true);
                txt_color.setVisible(true);
                txt_marca.setEditable(false);
                txt_modelo.setEditable(false);
                txt_color.setEditable(false);
                txt_nombre.setEditable(false);
                txt_apellido.setEditable(false);
                txt_email.setEditable(false);
                txt_telefono.setEditable(false);
                txt_domicilio.setEditable(false);
                btn_tom_foto.setEnabled(true); 
            } else {
                JOptionPane.showMessageDialog(this, "PLACA NO ENCONTRADA \n\n  INGRESE DATOS");
                serv.valor1 = 0;
                restaurar();
                btn_cliente_nuevo.setEnabled(true);
                btn_buscar_cliente.setEnabled(true);
            }// if si hay datos registrados 
        }// else campo placa vacio  
    }//GEN-LAST:event_btn_buscar_placaActionPerformed

    private void btn_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registrarActionPerformed
        if(serv.valor1 == 0 ){
            serv.Reg_datos_comb();
            limpiar();
            restaurar();
            this.dispose();
        } else {
            serv.Reg_datos_txt();
            this.dispose();
        }// error al insertar       
    }//GEN-LAST:event_btn_registrarActionPerformed

    private void btn_cliente_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cliente_nuevoActionPerformed
        serv.cont_nuevo_cli();
        System.out.println("este es el valor1: " + serv.valor1); 
        txt_nombre.setEditable(true);
        txt_apellido.setEditable(true);
        txt_email.setEditable(true);
        txt_telefono.setEditable(true);
        txt_domicilio.setEditable(true);
        btn_tom_foto.setEnabled(true);
    }//GEN-LAST:event_btn_cliente_nuevoActionPerformed

    private void btn_buscar_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscar_clienteActionPerformed
        if(txt_nombre.getText().toUpperCase().trim().equals("")){
            JOptionPane.showMessageDialog(this, "CAMPO VACIO:  INGRESE NOMBRE (S) ", "BUSCANDO CLIENTE...", 0);
        } else if (txt_apellido.getText().toUpperCase().trim().equals("")){
            JOptionPane.showMessageDialog(this, "CAMPO VACIO:  INGRESE APELLIDOS ", "BUSCANDO CLIENTE...", 0);
        } else {
            if(serv.buscar_Cliente(txt_nombre.getText().toUpperCase().replace("'", "").replace(";", "").replace("=", "").trim(),txt_apellido.getText().toUpperCase().trim()) == 1){
                JOptionPane.showMessageDialog(this, " CLIENTE ENCONTRADO", "BUSCANDO CLIENTE...", 2);
            } else {
                JOptionPane.showMessageDialog(this, " CLIENTE  NO ENCONTRADO", "BUSCANDO CLIENTE...", 0);
            }
            btn_tom_foto.setEnabled(true);
        }// campos vacios
    }//GEN-LAST:event_btn_buscar_clienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Orden_Servicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Orden_Servicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Orden_Servicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Orden_Servicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Orden_Servicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btn_buscar_cliente;
    public static javax.swing.JButton btn_buscar_placa;
    public static javax.swing.JButton btn_cliente_nuevo;
    public static javax.swing.JButton btn_registrar;
    public static javax.swing.JButton btn_tom_foto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JComboBox ob_color;
    public static javax.swing.JComboBox ob_marca;
    public static javax.swing.JTextField txt_apellido;
    public static javax.swing.JTextField txt_cliente;
    public static javax.swing.JTextField txt_color;
    public static javax.swing.JTextArea txt_diagnostico;
    public static javax.swing.JTextField txt_domicilio;
    public static javax.swing.JTextField txt_email;
    public static javax.swing.JLabel txt_hora_ent;
    public static javax.swing.JTextField txt_marca;
    public static javax.swing.JTextField txt_modelo;
    public static javax.swing.JTextField txt_nombre;
    public static javax.swing.JTextField txt_placa;
    public static javax.swing.JTextField txt_telefono;
    // End of variables declaration//GEN-END:variables
}
